version: '3'
services:
  frontend:
    image: ghost:1-alpine
    restart: always
    ports:
      - 2368:2368
    environment:
      - database__client=mysql
      - database__connection__database=ghost
      - database__connection__host=database
      - database__connection__user=root
      - database__connection__password=1234
    depends_on:
      - database
  database:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    
